import { awscdk, TextFile, YamlFile, DependencyType } from 'projen';
import { Dependabot, DependabotScheduleInterval, GithubCredentials, VersioningStrategy } from 'projen/lib/github';
import { NodePackageManager, NpmAccess } from 'projen/lib/javascript';

const cdkVersion = '2.85.0';
const minConstructsVersion = '10.0.5';
const devConstructsVersion = '10.0.5';
const cdkCliVersion = '2.1118.0';
const devNodeVersion = '24.8.0';
const minNodeVersion = '20.0.0';
const workflowNodeVersion = '24.x';
const minProjenVersion = '0.99.52';

const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Jayson Rawlins',
  authorAddress: 'JaysonJ.Rawlins@gmail.com',
  packageName: '@jjrawlins/cdk-git-tagger',
  description: 'CDK Aspect to tag resources with git metadata.  This provides a nice connection between the construct and the git repository.',
  keywords: ['cdk', 'git', 'metadata', 'tag', 'tagger'],
  repositoryUrl: 'https://github.com/JaysonRawlins/cdk-git-tagger.git',
  defaultReleaseBranch: 'main',
  license: 'Apache-2.0',
  minNodeVersion: minNodeVersion,
  workflowNodeVersion: workflowNodeVersion,
  cdkVersion: cdkVersion,
  cdkCliVersion: cdkCliVersion,
  projenVersion: minProjenVersion,
  projenrcTs: true,
  packageManager: NodePackageManager.PNPM,
  pnpmVersion: '11.13.0',
  name: '@jjrawlins/cdk-git-tagger',
  stability: 'stable',

  peerDeps: [
    `aws-cdk-lib@>=${cdkVersion} <3.0.0`,
    `constructs@>=${minConstructsVersion} <11.0.0`,
  ],
  deps: [],
  devDeps: [
    `aws-cdk@${cdkCliVersion}`,
    `aws-cdk-lib@${cdkVersion}`,
    '@types/fs-extra',
    '@types/lodash',
    '@types/node',
    'fs-extra',
    'glob',
  ],

  releaseToNpm: true,
  npmAccess: NpmAccess.PUBLIC,
  npmTrustedPublishing: true,

  publishToPypi: {
    distName: 'jjrawlins-cdk-git-tagger',
    module: 'jjrawlins_cdk_git_tagger',
    trustedPublishing: true,
  },
  publishToNuget: {
    dotNetNamespace: 'JJRawlins.CdkGitTagger',
    packageId: 'JJRawlins.CdkGitTagger',
    trustedPublishing: true,
  },
  publishToGo: {
    moduleName: 'github.com/JaysonRawlins/cdk-git-tagger',
    packageName: 'cdkgittagger',
    // The Go module is published into this same repo, so the workflow's own
    // token suffices — no PAT.
    githubTokenSecret: 'GITHUB_TOKEN',
    // Publish to a dedicated branch, not main: go resolution works off the
    // cdkgittagger/vX.Y.Z tags, and main's required build check
    // (require-build-green ruleset) would reject publib's direct push.
    gitBranch: 'go',
  },

  githubOptions: {
    projenCredentials: GithubCredentials.fromApp({
      appIdSecret: 'PROJEN_APP_ID',
      privateKeySecret: 'PROJEN_APP_PRIVATE_KEY',
    }),
    mergify: false,
    pullRequestLintOptions: {
      semanticTitleOptions: {
        types: ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'chore', 'revert', 'ci', 'build', 'deps', 'wip', 'release'],
      },
    },
  },

  depsUpgrade: false,
  buildWorkflowOptions: {
    mutableBuild: false,
  },

  workflowBootstrapSteps: [
    {
      name: 'Install Aikido Safe-Chain 1.5.3 (in-flight malware scanner, 7d minimum age)',
      run: [
        'echo "SAFE_CHAIN_MINIMUM_PACKAGE_AGE_HOURS=168" >> $GITHUB_ENV',
        'curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.5.3/install-safe-chain.sh | sh -s -- --ci',
      ].join('\n'),
    },
  ],

  gitignore: [
    // Never ignore cdkgittagger/ — the published Go module lives on the 'go'
    // branch (which inherits this .gitignore); publib's release commit is
    // `git rm` + copy + `git add .`, so ignoring it makes the add silently
    // skip the copy and the release commit deletes the module.
    '.dccache',
    '.yalc',
  ],
});

project.package.addField('resolutions', {
  'form-data': '^4.0.4',
  'aws-cdk-lib': `>=${cdkVersion} <3.0.0`,
  'constructs': devConstructsVersion,
  // The Aikido-cooldown exact pins that used to live here are gone: pnpm's
  // minimumReleaseAge (pnpm-workspace.yaml) age-gates the whole tree at
  // resolution time, transitives included.
});

project.package.addField('engines', {
  node: `>=${minNodeVersion}`,
});

project.deps.removeDependency('constructs');
project.deps.addDependency(`constructs@>=${minConstructsVersion} <11.0.0`, DependencyType.PEER);

new TextFile(project, '.tool-versions', {
  lines: [
    '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
    `nodejs ${devNodeVersion}`,
  ],
});

project.eslint?.addOverride({
  files: ['src/**/*.ts'],
  rules: {
    'import/no-extraneous-dependencies': ['error', {
      devDependencies: true,
      optionalDependencies: false,
      peerDependencies: true,
    }],
  },
});

project.compileTask.exec('rm -f tsconfig.json');

// =========================================================================
// Security baseline — see ../.claude/projen-security-baseline.ts.
// =========================================================================

const prLintWorkflow = project.github!.tryFindWorkflow('pull-request-lint');
if (prLintWorkflow) {
  prLintWorkflow.file!.addOverride(
    'jobs.validate.steps.0.uses',
    'amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50', // v6.1.1
  );
}

const dependabot = new Dependabot(project.github!, {
  scheduleInterval: DependabotScheduleInterval.WEEKLY,
  versioningStrategy: VersioningStrategy.LOCKFILE_ONLY,
  labels: ['dependencies'],
  openPullRequestsLimit: 10,
  cooldown: {
    defaultDays: 7,
    semverMinorDays: 7,
    // Keep every cooldown >= the pnpm minimumReleaseAge gate (7d): Dependabot
    // regenerates pnpm-lock.yaml with pnpm itself, which honors the committed
    // gate — a bump younger than the gate can't even create its PR
    // (dependabot-core#13165). With cooldown >= gate, PRs are born age-clean.
    semverPatchDays: 7,
    include: ['*'],
  },
  groups: {
    'aws-sdk': { patterns: ['@aws-sdk/*', '@smithy/*'] },
    'typescript-eslint': { patterns: ['@typescript-eslint/*'] },
    'jsii': { patterns: ['jsii', 'jsii-*'] },
    'eslint': { patterns: ['eslint', 'eslint-*', '@stylistic/*'] },
    'testing': { patterns: ['jest', 'jest-*', 'ts-jest'] },
    'types': { patterns: ['@types/*'] },
  },
});

dependabot.config.updates[0].ignore = [
  { 'dependency-name': 'projen' },
  { 'dependency-name': '*', 'update-types': ['version-update:semver-major'] },
];

dependabot.config.updates.push({
  'package-ecosystem': 'github-actions',
  'directory': '/',
  'schedule': { interval: 'weekly' },
  'open-pull-requests-limit': 0,
  'labels': ['dependencies', 'github-actions'],
});

new YamlFile(project, 'pnpm-workspace.yaml', {
  obj: {
    // 7d age gate applied at RESOLUTION time — covers transitives, which is
    // the gap Dependabot's cooldown can't close (it ages direct deps only).
    // Must stay <= every Dependabot cooldown above or bump PRs can't resolve.
    minimumReleaseAge: 10080,
    // jsii packaging needs a flat node_modules; pnpm's default isolated
    // linker breaks `pnpm pack` for bundledDependencies repos — hoisted is
    // the uniform baseline choice.
    nodeLinker: 'hoisted',
    allowBuilds: {
      // Transitive of eslint-import-resolver-typescript; ships prebuilt
      // binaries, its build script is an unneeded fallback.
      'unrs-resolver': false,
    },
  },
});

// Two-witness on the age gate: verify the ARTIFACT (every resolved version's
// registry publish date), not the resolver that produced it. Catches any
// update path — Dependabot, upgrade runs, or a human hand-editing the lock.
const auditTask = project.addTask('audit:lockfile-age', {
  exec: 'node .github/scripts/audit-lockfile-age.mjs pnpm-lock.yaml 168',
  description: 'Verify every pnpm-lock.yaml entry is at least 168h old on the registry',
});
project.buildWorkflow?.addPostBuildSteps({
  name: 'Audit lockfile age',
  run: `npx projen ${auditTask.name}`,
});

new YamlFile(project, '.github/workflows/security.yml', {
  obj: {
    name: 'security',
    on: { pull_request: {}, workflow_dispatch: {} },
    jobs: {
      security: { uses: 'JaysonRawlins/.github/.github/workflows/security.yml@main' },
    },
  },
});

new YamlFile(project, '.github/workflows/semgrep.yml', {
  obj: {
    name: 'Semgrep',
    on: {
      push: { branches: ['main'] },
      pull_request: { branches: ['main'] },
    },
    permissions: { 'contents': 'read', 'security-events': 'write' },
    jobs: {
      scan: {
        'name': 'Scan',
        'runs-on': 'ubuntu-latest',
        'container': {
          image: 'semgrep/semgrep@sha256:9349edbadf90c3f3c0c3f55867625354e89680e6fa10d9034042af52fdb0e0d0',
        },
        'steps': [
          { uses: 'actions/checkout@v4' },
          {
            name: 'Run Semgrep',
            run: [
              'semgrep scan \\',
              '  --config=p/security-audit \\',
              '  --config=p/typescript \\',
              '  --config=p/javascript \\',
              '  --config=p/nodejs \\',
              '  --sarif --output=semgrep.sarif \\',
              '  || true',
            ].join('\n'),
          },
          {
            'name': 'Upload SARIF',
            'if': "always() && hashFiles('semgrep.sarif') != ''",
            'continue-on-error': true,
            'uses': 'github/codeql-action/upload-sarif@f411752efdf656cb71aa17b755b22c890960da1d', // v3.35.5
            'with': { sarif_file: 'semgrep.sarif' },
          },
        ],
      },
    },
  },
});

new YamlFile(project, '.github/workflows/dependabot-automerge.yml', {
  obj: {
    name: 'dependabot-automerge',
    on: {
      pull_request_target: {
        types: ['opened', 'synchronize', 'reopened', 'ready_for_review'],
      },
    },
    permissions: { 'contents': 'write', 'pull-requests': 'write' },
    jobs: {
      automerge: {
        'runs-on': 'ubuntu-latest',
        'if': "github.actor == 'dependabot[bot]'",
        'steps': [
          {
            name: 'Get Dependabot metadata',
            id: 'metadata',
            uses: 'dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a', // v2.5.0
            with: { 'github-token': '${{ secrets.GITHUB_TOKEN }}' },
          },
          {
            name: 'Enable auto-merge for safe Dependabot PRs',
            if: "steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'",
            run: 'gh pr merge --auto --squash "$PR_URL"',
            env: {
              PR_URL: '${{ github.event.pull_request.html_url }}',
              GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
            },
          },
        ],
      },
    },
  },
});

new YamlFile(project, '.github/workflows/dependabot-rebase-stuck.yml', {
  obj: {
    name: 'dependabot-unblocker',
    on: {
      schedule: [{ cron: '0 9 * * 1' }],
      workflow_dispatch: {},
    },
    permissions: { 'pull-requests': 'read', 'actions': 'write' },
    jobs: {
      unblock: {
        'runs-on': 'ubuntu-latest',
        'steps': [
          {
            name: 'Rerun failed build on Aikido-cooldown-blocked Dependabot PRs',
            env: {
              GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
              REPO: '${{ github.repository }}',
            },
            run: [
              'set -euo pipefail',
              '',
              'stuck=$(gh pr list --repo "$REPO" \\',
              '  --author "app/dependabot" \\',
              '  --state open \\',
              '  --json number,statusCheckRollup \\',
              '  --jq \'.[] | select([.statusCheckRollup[] | select(.name == "build")] | any(.conclusion == "FAILURE")) | .number\')',
              '',
              'if [ -z "$stuck" ]; then',
              '  echo "No stuck Dependabot PRs."',
              '  exit 0',
              'fi',
              '',
              'for pr in $stuck; do',
              '  run_id=$(gh pr view "$pr" --repo "$REPO" --json statusCheckRollup \\',
              '    --jq \'.statusCheckRollup[] | select(.name == "build") | .detailsUrl\' \\',
              '    | grep -oE "/runs/[0-9]+" | head -1 | cut -d/ -f3)',
              '',
              '  if [ -z "$run_id" ]; then',
              '    echo "PR #$pr: no build run id, skipping"',
              '    continue',
              '  fi',
              '',
              '  log=$(gh run view "$run_id" --repo "$REPO" --log-failed 2>&1 || true)',
              '',
              '  if echo "$log" | grep -q "minimum package age"; then',
              '    echo "PR #$pr: Aikido cooldown block — rerunning failed build (preserves lockfile)"',
              '    gh run rerun "$run_id" --repo "$REPO" --failed',
              '  elif echo "$log" | grep -q "Safe-chain: blocked"; then',
              '    echo "PR #$pr: Aikido blocked (non-age, possibly malware) — leaving for human review"',
              '  else',
              '    echo "PR #$pr: build failed for unrecognized reason — leaving for human review"',
              '  fi',
              'done',
            ].join('\n'),
          },
        ],
      },
    },
  },
});

const releaseWorkflow = project.github!.tryFindWorkflow('release')!;
releaseWorkflow.file!.addOverride('jobs.release.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_pypi.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_pypi.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_nuget.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_nuget.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_golang.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_golang.permissions.contents', 'write');
// publib pushes via `https://<GITHUB_TOKEN>@github.com`, but the workflow's
// installation token only authenticates in the documented
// `x-access-token:<token>` userinfo form — bare, git dies with "could not
// read Password". Rewrite the URL inside git itself via env-based config
// (GIT_CONFIG_COUNT/KEY_0/VALUE_0, git >= 2.31) at the JOB level: immune to
// step-index drift, and doesn't clobber projen's packaging prePublishSteps.
releaseWorkflow.file!.addOverride('jobs.release_golang.env.GIT_CONFIG_COUNT', '1');
releaseWorkflow.file!.addOverride('jobs.release_golang.env.GIT_CONFIG_KEY_0', 'url.https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf');
releaseWorkflow.file!.addOverride('jobs.release_golang.env.GIT_CONFIG_VALUE_0', 'https://${{ secrets.GITHUB_TOKEN }}@github.com/');

project.synth();
